// Generated by CoffeeScript 1.7.1
(function() {
    $('#submit').click(function() {
        $('#add_empty').show();
        var input_first_name, input_last_name, phone, ul;
        ul = $('#numbers');
        input_first_name = $('#input_first_name').val();
        input_last_name = $('#input_last_name').val();
        phone = $('#input_phone').val();
        $(ul).prepend('<li><span id="span">Name: ' + input_first_name + ' ' + input_last_name + '  <br/>Number: ' + phone + '</span></li>');
        localStorage.setItem('contacts', $(ul).html());
        $("form")[0].reset();
        return false;
    });


    $('#clear_storage').click(function(){
        localStorage.clear();
        location.reload();
    });

    if (localStorage.getItem('contacts')) {
        $('#numbers').html(localStorage.getItem('contacts'));
    }
    var check_span = $("#span").html();

        if (check_span) {
            $('#add_empty').hide();
        }
        else {
            $('#add_empty').show();

        }


}).call(this);
